# Generated by Django 2.2.9 on 2020-01-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogames', '0005_auto_20200116_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='age',
            field=models.CharField(max_length=20),
        ),
    ]
