# Generated by Django 2.2.9 on 2020-01-21 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ogames', '0006_auto_20200116_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='city',
        ),
        migrations.RemoveField(
            model_name='event',
            name='season',
        ),
        migrations.RemoveField(
            model_name='event',
            name='year',
        ),
        migrations.AddField(
            model_name='athleteevent',
            name='city',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='athlete_events', to='ogames.City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='athleteevent',
            name='season',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='athleteevent',
            name='year',
            field=models.IntegerField(blank=True, default=None),
            preserve_default=False,
        ),
    ]
